### PR TITLE
App icon refresh

### PR DESCRIPTION
**Pull request by bertob**
I was playing with the icon a little bit and came up with this. Let me know if you want any changes.

- Various minor style tweaks to the notepad
- Add a pencil to make it feel more lively
- More distinctive symbolic
- Add .Source SVG file to repo

image

### CODE REVIEW

**Comment by lainsce** [comment]
Hmm.... two things... :smile:

1) The pencil looks tiny compared to Text Editor's
2) I think the pencil being black colored instead might help make it more visually catchy & distinct, blue pencils are outdated lol

**Comment by bertob** [comment]
> pencil looks tiny compared to Text Editor's

Not really. Maybe compared to Gedit, but that one isn't a good example for anything. With a fixed-size canvas object sizes depend on the context and the size of other objects on there, so naturally you'll get some variance in size for similar objects between different icons.

> I think the pencil being black colored instead might help make it more visually catchy & distinct

Personally I think I prefer the blue here, but no strong opinion.

image

**Comment by lainsce** [comment]
Alrighty, looks good. Merging~

Thanks for the icon help!

**Comment by lainsce** [comment]
(Don't worry, I did the black pencil thing)

**Pull request merged**
