### PR TITLE
build: use latest meson functions

### PR DESCRIPTION
**Pull request by oscfdezdz**
⚠️ Revert if dangerous ⚠️ 

I am concerned about this warning: `WARNING: CMake Toolchain: Failed to determine CMake compilers state`. Although everything seems to be working normally.

Not found build-time dependencies are not an issue from what I can see in other projects using these meson functions.

### CODE REVIEW

**Comment by lainsce** [comment]
I'll hold on in merging this until I am absolutely sure that the meson flathub is using has these functions, to avoid having to revert

**Comment by eli-schwartz** [comment]
The advantage of adding `meson_version: '>= 0.59.0'` to the project() declaration is that meson will tell you if you use functions that aren't guaranteed to be available in the meson_version you declare you support. :)

Meson will also abort with an error if it is too old.

I have no idea how flatpak works, but what version of meson do they use?

**Comment by lainsce** [comment]
Apparently flathub is using meson version 0.52 last I checked because of some functions in later meson versions breaking the release when I tried to publish there.

**Comment by eli-schwartz** [comment]
Then it sounds like this PR would cause flathub to fail with the informative error:

> Meson version is 0.52.0 but project requires 0.59.0

That being said, adding minimum version requirements is probably still a good idea, as it will help you better track what you need / can use. e.g.

```diff
diff --git a/meson.build b/meson.build
index 9c95e99..6641345 100644
--- a/meson.build
+++ b/meson.build
@@ -1,4 +1,6 @@
-project('io.github.lainsce.Notejot', ['vala', 'c'], version: '3.3.3')
+project('io.github.lainsce.Notejot', ['vala', 'c'],
+        version: '3.3.3',
+        meson_version: '>=0.32.0')
 gnome = import('gnome')
 i18n = import('i18n')
```

(The newest feature you are currently using is `0.46.0: {'rename arg in install_data'}`.)

**Comment by oscfdezdz** [comment]
I've checked other apps like GNOME Text Editor or Metadata Cleaner that are using, for example, Meson's gnome post_install function which is a feature introduced in Meson 0.57.0 (and 0.59.0 for `update_desktop_database`) and I don't see anything different in their manifests or build files to make it work for Flathub.

**Comment by lainsce** [comment]
> I've checked other apps like GNOME Text Editor or Metadata Cleaner that are using, for example, Meson's gnome post_install function which is a feature introduced in Meson 0.57.0 (and 0.59.0 for `update_desktop_database`) and I don't see anything different in their manifests or build files to make it work for Flathub.

That's weird, because when I merged your old PR that did these changes, I had to revert it...

Maybe flathub's meson updated then?

**Pull request merged**
