### PR TITLE
Update Spanish translation

### PR DESCRIPTION
**Pull request by oscfdezdz**
Depends on #217

### CODE REVIEW

**Comment by lainsce** [comment]
Uh, seems like a commit from the other PR is here, and a commit from here is in the other PR.

Can you divide the PRs properly? ;)

**Comment by oscfdezdz** [comment]
I think that if #217 is merged it should adjust itself. I updated the translation with that commit applied.
The .pot file is updated in https://github.com/lainsce/notejot/pull/218/commits/079f566c82070e776ed48aea97884fe63fcbc578 to add the new lines, but I can commit .pot and es.po together if that's better :)

**Comment by lainsce** [comment]
Yeah, if you could put the translation files here, and the code files over at the other PR, I'd be grateful.

**Comment by oscfdezdz** [comment]
Splited now, CI only runs on e870b575358d814f5cb40b45cb733ef2debebaaf in this PR, so it should adjust once #217 is merged, if not I'll change this one again.

**Comment by lainsce** [comment]
lgtm, merging both :)

**Comment by oscfdezdz** [comment]
Thanks! Seems like I had to separate the commits at the end, git didn't take into account that the last one was based on the previous one, good to know for next time.

**Pull request merged**
