### PR TITLE
build: minor changes

### PR DESCRIPTION
**Pull request by oscfdezdz**
Commit message:

```
- Add vcs taggging for development builds.
- Name prefix in development builds is now a suffix to match
  desktop file name.
```

### CODE REVIEW

**Comment by lainsce** [comment]
Just a quick glance, and I prefer to have the project name & exec be RDNN'd (io.github.lainsce.Notejot) instead of plain (notejot), to avoid collisions.

**Comment by oscfdezdz** [comment]
Any guesses on CI's failure?
`Error: icon io.github.lainsce.Notejot.Devel not found below /__w/notejot/notejot/flatpak_app/files/share/icons`

I think it is due to this line in the manifest:
`"rename-icon" : "io.github.lainsce.Notejot.Devel",`
 but if I remove it, it gives another error and I don't know what else it can be.

**Comment by lainsce** [comment]
> Any guesses on CI's failure? `Error: icon io.github.lainsce.Notejot.Devel not found below /__w/notejot/notejot/flatpak_app/files/share/icons`
> 
> I think it is due to this line in the manifest: `"rename-icon" : "io.github.lainsce.Notejot.Devel",` but if I remove it, it gives another error and I don't know what else it can be.

Perhaps it expects the icon to be xxx.xxx.xxx.xxxDevel and it doesn't find it?

**Comment by lainsce** [comment]
Now it's the .desktop file :p

**Comment by oscfdezdz** [comment]
> Now it's the .desktop file :p

Yes 😅 I tried with NotejotDevel but it gave the same icon error: https://github.com/lainsce/notejot/actions/runs/1509036097

**Comment by oscfdezdz** [comment]
There was something wrong with the change of the profile from string to bool, so I'll leave it as it is for now 😄

**Comment by lainsce** [comment]
Seems that it's fixed, so I'll merge.

**Pull request merged**
