### PR TITLE
Make the windows resizable and smaller

### PR DESCRIPTION
**Pull request by MonkeyAndres**

### CODE REVIEW

**Comment by lainsce** [comment]
Hi,

I noticed you're a first time contributor to Notejot.
I'm going right to the point: What does resizing and making the sticky notes smaller accomplish for you?
Is the default size too big for your screen? Is resizing necessary for you?

I ask both because Notejot is supposed to be a virtual sticky notes application, as such, it tries to emulate a real sticky note on your desktop. I wouldn't know of any resizable sticky note technology thing around in real life... (I would love that) But for Notejot, my design vision gets trumped with the addition of resizing.

**Comment by MonkeyAndres** [comment]
Hi,

I have a screen with a 1366x768 resolution and the notes are to big for the screen. Sorry for pull requesting, i don't know anything about your vision, keep it like you want :D

-------- Mensaje original --------

**Comment by lainsce** [comment]
Oh, so can you revert the resizing, and use the middle ground 400x400 as size?

**Comment by MonkeyAndres** [comment]
Okay, i do it in a moment. Thanks for everything :)

-------- Mensaje original --------

**Pull request merged**
